# Init

In [56]:
import duckdb
import pandas as pd

In [57]:
cd ..

/Users/wliao0504/Library/Mobile Documents/com~apple~CloudDocs

In [58]:
pwd

'/Users/wliao0504/Library/Mobile Documents/com~apple~CloudDocs'

In [59]:
%load_ext autoreload
%autoreload 2
from src.utils import check_duplicates, find_duplicates, read_from_rclif, clif_table_pathfinder, \
    mimic_table_pathfinder

from importlib import reload
import src.tables.respiratory_support
reload(src.tables.respiratory_support)
from src.tables.respiratory_support import RespPipeline
# reload(src.tables.respiratory_support.RespPipeline)
from src.utils import construct_mapper_dict, fetch_mimic_events, load_mapping_csv, \
    get_relevant_item_ids, find_duplicates, rename_and_reorder_cols, save_to_rclif, \
    convert_and_sort_datetime, setup_logging

2025-03-31 00:02:07,921 - INFO - initialized logging at logs/etl.log

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Dev

## Pipeline

In [60]:
p = RespPipeline()

In [61]:
p.run()

2025-03-31 00:02:09,799 - INFO - Starting respiratory_support pipeline
2025-03-31 00:02:09,800 - INFO - starting to build clif respiratory support table -- extracting source data from MIMIC-IV...
2025-03-31 00:02:09,807 - INFO - parsing the mapping files to identify relevant items and fetch corresponding events...
2025-03-31 00:02:09,808 - INFO - querying the d_items table to identify which event tables to be separately queried for 31 items
2025-03-31 00:02:09,811 - INFO - identified 2 event tables to be separately queried: ['chartevents', 'procedureevents']
2025-03-31 00:02:09,811 - INFO - fetching events from chartevents table for 29 items

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

2025-03-31 00:02:14,879 - INFO - fetched 13719827 events from chartevents table for 29 items
2025-03-31 00:02:14,880 - INFO - fetching events from procedureevents table for 2 items
2025-03-31 00:02:14,892 - INFO - fetched 680 events from procedureevents table for 2 items
2025-03-31 00:02:15,102 - INFO - concatenated 13720507 events from 2 event tables
2025-03-31 00:02:17,598 - INFO - identified 125741 'duplicated' events to be cleaned.
2025-03-31 00:02:17,598 - INFO - removing the first type of duplicates: lower-ranked 'duplicated' devices...
2025-03-31 00:02:20,722 - INFO - removing the second type of duplicates: duplicated device reads...
2025-03-31 00:02:24,911 - INFO - pivoting to a wide format and coalescing duplicate columns...
/Users/wliao0504/Library/Mobile Documents/com~apple~CloudDocs/Repo/hca-lab/CLIF-MIMIC/src/tables/respiratory_support.py:230: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  resp_wider_in_ids["tracheostomy"] = resp_wider_in_ids[225448].fillna(
2025-03-31 00:02:31,164 - INFO - mapping device and mode names to categories...
2025-03-31 00:02:31,977 - INFO - renaming, reordering, and re-casting columns...
2025-03-31 00:02:34,874 - INFO - imputing whether tracheostomy had been performed at the time of observation...
2025-03-31 00:02:38,646 - INFO - saving respiratory_support rclif table as a parquet file at /Users/wliao0504/Library/Mobile Documents/com~apple~CloudDocs/Repo/hca-lab/CLIF-MIMIC/src/../output/rclif-dev-test/clif_respiratory_support.parquet.
2025-03-31 00:02:39,428 - INFO - Saved respiratory_support to parquet file
2025-03-31 00:02:39,429 - INFO - Completed respiratory_support pipeline successfully

In [62]:
p.data.keys()

dict_keys(['extract', '_remove_none_value_rows', '_remove_duplicates', '_pivot_and_coalesce', '_rename_reorder_recast_cols', '_clean_fio2_set', '_clean_tracheostomy', 'transform'])

## Check NA

In [63]:
resp_f = read_from_rclif("respiratory_support")

In [64]:
# get the final df which is the output of the `transform` step in the pipeline
resp_f = p.data["transform"]
print(len(resp_f))
resp_f.head()

2148669

,hospitalization_id,recorded_dttm,device_name,device_category,vent_brand_name,mode_name,mode_category,tracheostomy,fio2_set,lpm_set,...,peak_inspiratory_pressure_set,inspiratory_time_set,peep_set,tidal_volume_obs,resp_rate_obs,plateau_pressure_obs,peak_inspiratory_pressure_obs,peep_obs,minute_vent_obs,mean_airway_pressure_obs
0,20000094,2150-03-02 15:34:00,Nasal cannula,Nasal Cannula,NaN,NaN,NaN,False,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,20000094,2150-03-02 20:00:00,Nasal cannula,Nasal Cannula,NaN,NaN,NaN,False,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,20000147,2121-08-30 22:00:00,Endotracheal tube,IMV,NaN,CMV/ASSIST/AutoFlow,Assist Control-Volume Control,False,1.0,NaN,...,NaN,0.9,5.0,524.0,16.0,23.0,25.0,NaN,9.77,11.0
3,20000147,2121-08-30 23:00:00,NaN,None,Drager,CMV/ASSIST/AutoFlow,Assist Control-Volume Control,False,NaN,NaN,...,NaN,0.9,10.0,612.0,18.0,22.0,24.0,10.2,9.90,10.0
4,20000147,2121-08-31 00:00:00,NaN,None,NaN,NaN,NaN,False,0.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
# create a new column called "all_value_na" if all the columns starting from "tracheostomy" are NA
resp_f["all_value_na"] = resp_f.loc[:, "fio2_set": "mean_airway_pressure_obs"].isna().all(axis=1)
resp_f.head()

,hospitalization_id,recorded_dttm,device_name,device_category,vent_brand_name,mode_name,mode_category,tracheostomy,fio2_set,lpm_set,...,inspiratory_time_set,peep_set,tidal_volume_obs,resp_rate_obs,plateau_pressure_obs,peak_inspiratory_pressure_obs,peep_obs,minute_vent_obs,mean_airway_pressure_obs,all_value_na
0,20000094,2150-03-02 15:34:00,Nasal cannula,Nasal Cannula,NaN,NaN,NaN,False,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1,20000094,2150-03-02 20:00:00,Nasal cannula,Nasal Cannula,NaN,NaN,NaN,False,NaN,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
2,20000147,2121-08-30 22:00:00,Endotracheal tube,IMV,NaN,CMV/ASSIST/AutoFlow,Assist Control-Volume Control,False,1.0,NaN,...,0.9,5.0,524.0,16.0,23.0,25.0,NaN,9.77,11.0,False
3,20000147,2121-08-30 23:00:00,NaN,None,Drager,CMV/ASSIST/AutoFlow,Assist Control-Volume Control,False,NaN,NaN,...,0.9,10.0,612.0,18.0,22.0,24.0,10.2,9.90,10.0,False
4,20000147,2121-08-31 00:00:00,NaN,None,NaN,NaN,NaN,False,0.5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [66]:
# a smaller subsect of important columns to inspect
resp_f2: pd.DataFrame = resp_f[
    [
        "hospitalization_id",
        "recorded_dttm",
        "device_name", "device_category",
        "vent_brand_name",
        "mode_name", "mode_category",
        "all_value_na",
    ]
]
resp_f2.head()

,hospitalization_id,recorded_dttm,device_name,device_category,vent_brand_name,mode_name,mode_category,all_value_na
0,20000094,2150-03-02 15:34:00,Nasal cannula,Nasal Cannula,NaN,NaN,NaN,False
1,20000094,2150-03-02 20:00:00,Nasal cannula,Nasal Cannula,NaN,NaN,NaN,False
2,20000147,2121-08-30 22:00:00,Endotracheal tube,IMV,NaN,CMV/ASSIST/AutoFlow,Assist Control-Volume Control,False
3,20000147,2121-08-30 23:00:00,NaN,None,Drager,CMV/ASSIST/AutoFlow,Assist Control-Volume Control,False
4,20000147,2121-08-31 00:00:00,NaN,None,NaN,NaN,NaN,False

Notice there are both 'None' and NaN (null) in `device_name`. NaN are likely the rows with partial values while None likely correspond to rows that are completely NA -- need to check this.

In [67]:
resp_f.value_counts(["device_name"], dropna=False)

device_name
Endotracheal tube          633302
NaN                        542983
Nasal cannula              519136
Tracheostomy tube          127409
Aerosol-cool                74701
Trach mask                  50219
High flow nasal cannula     47831
Face tent                   43960
Bipap mask                  25813
High flow neb               18577
Oxymizer                    16981
Non-rebreather              13610
CPAP mask                   10764
T-piece                      7855
Venti mask                   6275
Medium conc mask             4718
Other                        4509
Ultrasonic neb                 20
Vapomist                        6
Name: count, dtype: int64

In [68]:
resp_f.value_counts(["mode_name"], dropna=False)

mode_name
NaN                                  1273997
CPAP/PSV                              203473
CMV/ASSIST/AutoFlow                   184695
APV (cmv)                             173135
SPONT                                 163902
ASV                                    32439
CMV/ASSIST                             19652
MMV/PSV/AutoFlow                       13344
Standby                                11997
Spontaneous (S)                        11872
PSV/SBT                                11357
P-CMV                                   8770
PRVC/AC                                 5342
PCV+Assist                              4336
CPAP/PSV+ApnVol                         3583
VS                                      3471
Spontaneous/Timed (S/T) (Back up)       2374
Ambient                                 2150
SIMV/PSV/AutoFlow                       2033
MMV/PSV                                 1981
NIV                                     1948
APRV                                    1916
CPAP                                    1380
(S) CMV                                 1207
CMV/AutoFlow                            1109
CMV                                     1033
CPAP/PPS                                 998
VOL/AC                                   933
CPAP/PSV+ApnPres                         815
PCV+                                     476
PCV+/PSV                                 417
SIMV/PSV                                 413
Not applicable                           363
NIV-ST                                   341
PRES/AC                                  329
APV (simv)                               218
MMV                                      211
Apnea Ventilation                        135
APRV/Biphasic+ApnVol                     106
SIMV                                     104
MMV/AutoFlow                              68
P-SIMV                                    46
SIMV/PRES                                 39
APRV/Biphasic+ApnPress                    34
PRVC/SIMV                                 27
Timed (T)                                 17
SIMV/AutoFlow                             16
SYNCHRON MASTER                           16
DuoPaP                                    16
CPAP/PSV+Apn TCPL                         15
SIMV/VOL                                  11
SYNCHRON SLAVE                             5
nCPAP-PS                                   4
Name: count, dtype: int64

In [82]:
print(f"{resp_f2.all_value_na.sum()} ({resp_f2.all_value_na.mean()*100:.1f}%) rows that have NA in all values fields.")

mask = resp_f2["device_name"].isna()
print(f"{mask.sum()} ({mask.mean()*100:.1f}%) rows have NaN for `device_name`")

mask = resp_f2["device_name"] == "None"
print(f"{mask.sum()} ({mask.mean()*100:.1f}%) rows have 'None' for `device_name`")

176044 (8.2%) rows that have NA in all values fields.
542983 (25.3%) rows have NaN for `device_name`
0 (0.0%) rows have 'None' for `device_name`

In [70]:
# filter rows with any NA -- in either device_name or across all value fields
mask = resp_f2["device_name"].isna() | (resp_f2["device_name"] == "None") | resp_f2["all_value_na"]
resp_f3 = resp_f2[mask]
resp_f3.head()

,hospitalization_id,recorded_dttm,device_name,device_category,vent_brand_name,mode_name,mode_category,all_value_na
3,20000147,2121-08-30 23:00:00,NaN,None,Drager,CMV/ASSIST/AutoFlow,Assist Control-Volume Control,False
4,20000147,2121-08-31 00:00:00,NaN,None,NaN,NaN,NaN,False
34,20001305,2178-03-26 17:30:00,NaN,None,NaN,APV (cmv),Pressure-Regulated Volume Control,False
35,20001305,2178-03-26 17:45:00,NaN,None,NaN,NaN,NaN,False
43,20001361,2143-05-04 17:04:00,NaN,None,NaN,NaN,NaN,False

Let's try to answer the following questions: 
1. are all the 'None' device_name followed up by all-NA values?

In [71]:
mask = resp_f2["device_name"] == "None"
resp_f4 = resp_f2[mask]
resp_f4.value_counts(["all_value_na"])

Series([], Name: count, dtype: int64)

So the answer is no -- then let's check out the rows with 'None' device_name but was still somehow filled by some values.

In [72]:
mask = (resp_f["device_name"] == "None") & (resp_f["all_value_na"] == False)
resp_f5 = resp_f[mask]       
print(f" there are {len(resp_f5)} ({mask.mean()*100:.2f}%) rows that have 'None' device_name but was still somehow filled by some values")
resp_f5.head()

 there are 0 (0.00%) rows that have 'None' device_name but was still somehow filled by some values

Empty DataFrame
Columns: [hospitalization_id, recorded_dttm, device_name, device_category, vent_brand_name, mode_name, mode_category, tracheostomy, fio2_set, lpm_set, tidal_volume_set, resp_rate_set, pressure_control_set, pressure_support_set, flow_rate_set, peak_inspiratory_pressure_set, inspiratory_time_set, peep_set, tidal_volume_obs, resp_rate_obs, plateau_pressure_obs, peak_inspiratory_pressure_obs, peep_obs, minute_vent_obs, mean_airway_pressure_obs, all_value_na]
Index: []

[0 rows x 26 columns]

verify from the untransformed MIMIC data that 'None' value were already occuring:

In [73]:
src_df = p.data["extract"]
src_df.head()

,itemid,label,hadm_id,stay_id,time,value,valueuom,variable
0,223834,O2 Flow,25563031,31205490,2110-04-12 06:00:00,2,L/min,lpm_set
1,226732,O2 Delivery Device(s),25563031,31205490,2110-04-12 06:00:00,Nasal cannula,None,device_name
2,223834,O2 Flow,25563031,31205490,2110-04-11 16:07:00,2,L/min,lpm_set
3,226732,O2 Delivery Device(s),25563031,31205490,2110-04-11 16:07:00,Nasal cannula,None,device_name
4,223835,Inspired O2 Fraction,26133978,39698942,2134-12-06 08:00:00,40,None,fio2_set

In [74]:
# find all the rows with value = None:
cond = src_df["value"] == 'None'
print(f"{cond.sum()} ({cond.mean()*100:.1f}%) has None value")
null_val_rows = src_df[cond]
null_val_rows.head()

398249 (2.9%) has None value

,itemid,label,hadm_id,stay_id,time,value,valueuom,variable
286,226732,O2 Delivery Device(s),23559586,38383343,2137-08-27 13:00:00,None,None,device_name
287,226732,O2 Delivery Device(s),23559586,38383343,2137-08-27 17:17:00,None,None,device_name
1022,226732,O2 Delivery Device(s),27793700,34672098,2162-02-20 12:00:00,None,None,device_name
1023,226732,O2 Delivery Device(s),27793700,34672098,2162-02-20 16:00:00,None,None,device_name
1724,226732,O2 Delivery Device(s),23251352,31494479,2141-12-18 11:00:00,None,None,device_name

And all of these occur on the same variable:

In [77]:
null_val_rows.value_counts(["variable", "label"])

variable     label
device_name  O2 Delivery Device(s)    398249
Name: count, dtype: int64

test which dropping is faster:

In [75]:
cond = src_df["value"] == 'None'
_ =src_df[~cond]

In [76]:
_ = src_df.query("value != 'None'")

also check our mapping didn't introduce any redundant stuff:

In [78]:
p.resp_mapper

{226732: 'device_name',
 223835: 'fio2_set',
 220339: 'peep_set',
 224685: 'tidal_volume_obs',
 224687: 'minute_vent_obs',
 224697: 'mean_airway_pressure_obs',
 224695: 'peak_inspiratory_pressure_obs',
 223834: 'lpm_set',
 223848: 'vent_brand_name',
 224690: 'resp_rate_obs',
 223849: 'mode_name',
 224688: 'resp_rate_set',
 224684: 'tidal_volume_set',
 224738: 'inspiratory_time_set',
 224686: 'tidal_volume_obs',
 224701: 'pressure_support_set',
 224696: 'plateau_pressure_obs',
 229314: 'mode_name',
 224691: 'flow_rate_set',
 224700: 'peep_obs',
 225448: 'tracheostomy',
 226237: 'tracheostomy',
 227287: 'lpm_set',
 224422: 'resp_rate_obs',
 224421: 'tidal_volume_obs',
 227577: 'mode_name',
 227579: 'peep_set',
 227580: 'peak_inspiratory_pressure_set',
 227582: 'flow_rate_set',
 224702: 'pressure_control_set',
 227581: 'resp_rate_set',
 None: None,
 'None': None}

In [79]:
p.resp_mode_mapper

{'CPAP/PSV': 'Pressure Support/CPAP',
 'CMV/ASSIST/AutoFlow': 'Assist Control-Volume Control',
 'CMV/ASSIST': 'Assist Control-Volume Control',
 'MMV/PSV/AutoFlow': 'Other',
 'PSV/SBT': 'Pressure Support/CPAP',
 'PRVC/AC': 'Pressure-Regulated Volume Control',
 'PCV+Assist': 'Pressure Control',
 'CPAP/PSV+ApnVol': 'Pressure-Regulated Volume Control',
 'SIMV/PSV/AutoFlow': 'SIMV',
 'MMV/PSV': 'Other',
 'CPAP': 'Pressure Support/CPAP',
 'APRV': 'Other',
 'CMV/AutoFlow': 'Assist Control-Volume Control',
 'CPAP/PPS': 'Pressure Support/CPAP',
 'CPAP/PSV+ApnPres': 'Pressure Support/CPAP',
 'VOL/AC': 'Assist Control-Volume Control',
 'PCV+': 'Pressure Control',
 'CMV': 'Assist Control-Volume Control',
 'PCV+/PSV': 'Pressure Control',
 'PRES/AC': 'Assist Control-Volume Control',
 'SIMV/PSV': 'SIMV',
 'APV (cmv)': 'Pressure-Regulated Volume Control',
 'SPONT': 'Pressure Support/CPAP',
 'MMV': 'Other',
 'Apnea Ventilation': 'Blow by',
 'APRV/Biphasic+ApnVol': 'Other',
 'MMV/AutoFlow': 'Other',
 'APRV/Biphasic+ApnPress': 'Pressure-Regulated Volume Control',
 'SIMV/PRES': 'SIMV',
 'PRVC/SIMV': 'Other',
 'SIMV': 'SIMV',
 'SIMV/AutoFlow': 'SIMV',
 'SYNCHRON MASTER': 'SIMV',
 'CPAP/PSV+Apn TCPL': 'Pressure Support/CPAP',
 'SIMV/VOL': 'SIMV',
 'SYNCHRON SLAVE': 'Other',
 'P-CMV': 'Pressure Control',
 '(S) CMV': 'Assist Control-Volume Control',
 'ASV': 'Other',
 'VS': 'Pressure Support/CPAP',
 'NIV': 'Other',
 'NIV-ST': 'Pressure Support/CPAP',
 'APV (simv)': 'SIMV',
 'P-SIMV': 'SIMV',
 'DuoPaP': 'Pressure Support/CPAP',
 'nCPAP-PS': 'Pressure Support/CPAP',
 'Spontaneous (S)': 'Other',
 'Spontaneous/Timed (S/T) (Back up)': 'Other',
 'Not applicable': 'Other',
 'Timed (T)': 'Other',
 nan: nan}

In [80]:
p.resp_device_mapper

{'Endotracheal tube': 'IMV',
 'Nasal cannula': 'Nasal Cannula',
 'Tracheostomy tube': 'IMV',
 'Aerosol-cool': 'Face Mask',
 'Face tent': 'Face Mask',
 'Trach mask': 'Trach Collar',
 'High flow nasal cannula': 'High Flow NC',
 'Bipap mask': 'NIPPV',
 'High flow neb': 'High Flow NC',
 'Non-rebreather': 'Face Mask',
 'CPAP mask': 'CPAP',
 'Venti mask': 'Face Mask',
 'Other': 'Other',
 'Medium conc mask': 'Face Mask',
 'Oxymizer': 'Face Mask',
 'T-piece': 'Other',
 'Ultrasonic neb': 'Other',
 'Vapomist': 'Other',
 nan: nan,
 None: None,
 'None': None}

In [81]:
resp_mapping = load_mapping_csv("respiratory_support")
resp_mapping.head()

,variable,itemid,label,abbreviation,linksto,category,unitname,param_type,count,value_instances,note / comment,status,latest update date,Unnamed: 13,variables,count.1,itemid_prio,label_prio,note
0,MAPPED ELSEWHERE,220210,Respiratory Rate,RR,chartevents,Respiratory,insp/min,Numeric,6393762,"Max: 2355560.0, Min: 0.0, Mean: 20.45996459206...",mapped in vitals,coded/validated by K. Smith,"July 2, 2024",NaN,tracheostomy,2.0,225448.0,Percutaneous Tracheostomy,likely no conflict
1,MAPPED ELSEWHERE,220277,O2 saturation pulseoxymetry,SpO2,chartevents,Respiratory,%,Numeric,6324341,"Max: 9900000.0, Min: -272.0, Mean: 104.8276359...",mapped in vitals,coded/validated by K. Smith,"July 2, 2024",NaN,fio2_set,1.0,NaN,NaN,NaN
2,device_name,226732,O2 Delivery Device(s),O2 Delivery Device(s),chartevents,Respiratory,NaN,Text,1536870,"""{'Endotracheal tube': 467931, 'Nasal cannula'...",NaN,coded/validated by K. Smith,"July 2, 2024",NaN,lpm_set,2.0,223834.0,O2 Flow,NaN
3,fio2_set,223835,Inspired O2 Fraction,FiO2,chartevents,Respiratory,NaN,Numeric,849875,"Max: 10050.0, Min: 0.0, Mean: 48.94540639505812",NaN,coded/validated by K. Smith,"July 2, 2024",NaN,tidal_volume_set,1.0,NaN,NaN,NaN
4,peep_set,220339,PEEP set,PEEP set,chartevents,Respiratory,cmH2O,Numeric,642089,"Max: 8774580.0, Min: -5.0, Mean: 26.2141163608...",NaN,coded/validated by K. Smith,"July 2, 2024",NaN,tidal_volume_obs,3.0,224685.0,Tidal Volume (observed),NaN